Asdoria\SyliusFacetFilterPlugin\Entity\FacetTranslation:
    properties:
        locale:
            - NotBlank:
                groups: [sylius]
        title:
            - NotBlank:
                groups: [sylius]
